language: rust

rust: nightly

addons:
  apt:
    packages:
      - libssh2-1
      - xorriso

install:
  - sudo apt-get install grub-common
  - export PATH="$PATH:$(rustc --print sysroot)/cargo/bin"
  - curl -sf "https://raw.githubusercontent.com/japaric/rust-everywhere/master/install.sh" | bash -s -- --from japaric/xargo

script:
  - xargo build --target x86 --release
  - readelf -hS target/x86/release/kernel
  - objdump -pCD target/x86/release/kernel
  - size target/x86/release/kernel
  - ./mk-iso.sh

branches:
  only:
    - auto
    - try

notifications:
  email:
    on_success: never
  webhooks: https://homu.herokuapp.com/travis
